'use client';
import { ArrowUpRight, ArrowDown, Plus } from 'lucide-react';
import RotatingEarth from '@/components/ui/wireframe-dotted-globe';
import {SiteNav} from '@/components/site-header';
import {categories,categoryPhotos} from '@/lib/gallery';
const photos=categories.map(category=>({...category,...categoryPhotos(category.slug)[0],category:category.name,title:category.description,image:categoryPhotos(category.slug)[0]?.src}));
export default function Home(){
 return <>
 <main id="main-content"><section className="intro globe-intro"><RotatingEarth width={1800} height={1800} className="hero-globe-background"/><div className="folio-meta"><span>PHOTOGRAPHER & STORYTELLER</span><span>PORTFOLIO / VOL. 01</span></div><h1 className="name-title"><span className="name-first">Allan</span> <span className="name-last">Kamuran</span><sup>(AK)</sup></h1><SiteNav home/><div className="hero-stage"><p className="hero-note"><span aria-hidden="true">✦</span>WEDDINGS. STREET.<br/>TRAVEL. PEOPLE.</p><p className="hero-note"><span aria-hidden="true">✦</span>HOLDING ON TO<br/>HOW IT FELT.</p></div><div className="intro-bottom"><span>PHOTOGRAPHS BY ALLAN KAMURAN</span><a href="#work">SCROLL TO EXPLORE <ArrowDown size={16}/></a></div></section>
 <section className="work-section" id="work"><div className="section-heading"><span className="eyebrow">(01—04) SELECTED PHOTOGRAPHS</span><h2>My <em>work.</em></h2><p>A collection of moments.<br/>Each with a story of its own.</p></div>
 <section className="gallery" aria-label="Selected photographs">{photos.map((photo,i)=><figure className={'photo photo-'+i} key={photo.image}><a className="photo-button" href={'/work/'+['travel','street','weddings','people'][i]} aria-label={'Explore '+photo.category}><img src={photo.image} alt={photo.alt} loading={i===0?'eager':'lazy'}/><span className="photo-index">0{i+1} / {photo.category.toUpperCase()}</span><span className="photo-open"><Plus size={24}/></span></a><figcaption><div><span>{photo.category}</span><h2>{photo.title}</h2></div><ArrowUpRight size={22}/></figcaption></figure>)}</section></section>
 <section className="about" id="about"><div className="about-label"><span className="eyebrow">(02) BEHIND THE CAMERA</span><h2>A little<br/><em>about me.</em></h2><img className="about-portrait" src="/photos/allan-profile.webp" alt="Allan Kamuran standing on a balcony with a mountain landscape behind him" loading="lazy"/></div><div className="about-copy"><h3>Life, as it unfolds.</h3><p>I’m Allan, and I’ve loved taking photographs since I was young. What began as something I simply loved doing has become a way of holding on to the people, places, and moments that matter to me.</p><p>That feeling is still at the heart of every photograph I take. A wedding full of laughter, a family waiting to welcome someone new, or time spent with someone you’ve grown up alongside — these moments mean something long before a camera is raised. Being trusted to capture them is something I’m deeply grateful for.</p><p>I’m just as drawn to the quieter things: a passing scene on the street, a face with a story, or a moment of stillness somewhere new. I use different kinds of cameras, from digital to film. Each brings its own rhythm and character to the way I see, but my aim is always the same: to make photographs that feel personal and honest.</p><p>More than anything, I hope the photographs I make help you remember how it felt to be there. That’s what keeps me reaching for my camera.</p></div></section>
 </main>
</>
}
