'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowDown, Plus } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const photos = [
 {category:'Nature',title:'Quiet, on a grand scale',image:'https://images.unsplash.com/photo-1725988551310-d33a492a6714?auto=format&fit=crop&w=2000&q=85',alt:'A stream running through a dramatic mountain range',credit:'Slava Auchynnikau',source:'https://unsplash.com/photos/usa9zjb7O3Y'},
 {category:'Street',title:'The geometry of everyday',image:'https://images.unsplash.com/photo-1746911779503-f16ee2088257?auto=format&fit=crop&w=1600&q=85',alt:'Repeating concrete forms of a brutalist building',credit:'Chris Johnson',source:'https://unsplash.com/photos/37zoajcSupg'},
 {category:'Weddings',title:'A day to hold onto',image:'https://images.unsplash.com/photo-1708569177091-d93e951adb1d?auto=format&fit=crop&w=1800&q=85',alt:'Bride and groom kissing as they walk down the aisle',credit:'Kari Bjorn Photography',source:'https://unsplash.com/photos/Jzvb59vRVWs'},
 {category:'People',title:'In a different light',image:'https://images.unsplash.com/photo-1495462911434-be47104d70fa?auto=format&fit=crop&w=1600&q=85',alt:'Black and white portrait of a woman wearing a hat with eyes closed',credit:'Luke Braswell',source:'https://unsplash.com/photos/8BxRYuPkzkU'},
];
export default function Home(){
 const [selected,setSelected]=useState<number|null>(null);
 return <>
 <main id="main-content"><section className="intro"><div className="folio-meta"><span>PHOTOGRAPHER & STORYTELLER</span><span>PORTFOLIO / VOL. 01</span></div><h1 className="name-title"><span className="name-first">Allan</span> <span className="name-last">Kamuran</span><sup>(AK)</sup></h1><div className="hero-stage"><p className="hero-note"><span aria-hidden="true">✦</span>WEDDINGS. STREET.<br/>NATURE. PEOPLE.</p><a className="hero-illustration" href="#work" aria-label="Explore selected photographs"><img src="/photographer.png" alt="Line illustration of a seated photographer holding a camera"/><span aria-hidden="true">✦</span><small>Always looking a little closer.</small></a><p className="hero-note"><span aria-hidden="true">✦</span>HOLDING ON TO<br/>HOW IT FELT.</p></div><div className="intro-bottom"><span>DESIGN PREVIEW · SAMPLE PHOTOGRAPHY</span><a href="#work">SCROLL TO EXPLORE <ArrowDown size={16}/></a></div></section>
 <section className="work-section" id="work"><div className="section-heading"><span className="eyebrow">(01—04) SELECTED PHOTOGRAPHS</span><h2>My <em>work.</em></h2><p>A collection of moments.<br/>Each with a story of its own.</p></div>
 <section className="gallery" aria-label="Selected photographs">{photos.map((photo,i)=><figure className={'photo photo-'+i} key={photo.image}><button className="photo-button" onClick={()=>setSelected(i)} aria-label={'Enlarge '+photo.alt}><img src={photo.image} alt={photo.alt} loading={i===0?'eager':'lazy'}/><span className="photo-index">0{i+1} / {photo.category.toUpperCase()}</span><span className="photo-open"><Plus size={24}/></span></button><figcaption><div><span>{photo.category}</span><h2>{photo.title}</h2></div><ArrowUpRight size={22}/></figcaption></figure>)}</section></section>
 <section className="about" id="about"><div className="about-label"><span className="eyebrow">(02) BEHIND THE CAMERA</span><h2>A little<br/><em>about me.</em></h2><span className="about-star" aria-hidden="true">✦</span></div><div className="about-copy"><h3>Life, as it unfolds.</h3><p>I’m Allan, and I’ve loved taking photographs since I was young. What began as something I simply loved doing has become a way of holding on to the people, places, and moments that matter to me.</p><p>That feeling is still at the heart of every photograph I take. A wedding full of laughter, a family waiting to welcome someone new, or time spent with someone you’ve grown up alongside — these moments mean something long before a camera is raised. Being trusted to capture them is something I’m deeply grateful for.</p><p>I’m just as drawn to the quieter things: a passing scene on the street, a face with a story, or a moment of stillness in nature. Whether I’m shooting digitally or on film, I want to make photographs that feel personal and honest.</p><p>More than anything, I hope the photographs I make help you remember how it felt to be there. That’s what keeps me reaching for my camera.</p><p className="draft-note">Portfolio in progress. The photographs shown here are sample images, not work by Allan Kamuran.</p></div></section>
 </main>
 <Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="photo-dialog">{selected!==null&&<><DialogTitle>{photos[selected].title}</DialogTitle><img src={photos[selected].image} alt={photos[selected].alt}/><DialogDescription>Sample photograph by <a href={photos[selected].source} target="_blank" rel="noreferrer">{photos[selected].credit} / Unsplash</a>. Not work by Allan Kamuran.</DialogDescription></>}</DialogContent></Dialog></>
}
